### ISSUE TITLE
One line arrow functions

### ISSUE THREAD

**Issue by farishkash** [saecollins/jamming_project#1]
https://github.com/saecollins/jamming_project/blob/3e5c76aa3fce5c3abedd3500fedb0d7038aa9624/src/util/Spotify.js#L97-L98

The return is implicit when the arrow function is one line.  You can remove the brackets and remove the return.  Test with yours and working below.

```
})
        .then(response => response.json())
        .then(jsonResponse => (playlistID = jsonResponse.id));
    }
```

**Comment by saecollins** [comment]
Thanks! I keep forgetting that -- I'll update Spotify.js and scan the otherwise for other examples.
