### ISSUE TITLE
Save PlayList

### ISSUE THREAD

**Issue by farishkash** [saecollins/jamming_project#2]
https://github.com/saecollins/jamming_project/blob/3e5c76aa3fce5c3abedd3500fedb0d7038aa9624/src/util/Spotify.js#L102-L103

I am really thinking about this one.  A lot of the project is being pushed in one direction that I feel goes away with what we are trying to convey.  The idea here was to pull the user id and playlist id from the initial fetch request but not make them into separate functions.

Yes, your project works, but this just doesn't seem elegant.

This is the approach we are looking for.

```
savePlaylist(name, trackUris) {
    if (!name || !trackUris.length) {
      return;
    }

    const accessToken = Spotify.getAccessToken();
    const headers = { Authorization: `Bearer ${accessToken}` };
    let userId;

    return fetch('https://api.spotify.com/v1/me', {headers: headers}
    ).then(response => response.json()
    ).then(jsonResponse => {
      userId = jsonResponse.id;
      return fetch(`https://api.spotify.com/v1/users/${userId}/playlists`, {
        headers: headers,
        method: 'POST',
        body: JSON.stringify({name: name})
      }).then(response => response.json()
      ).then(jsonResponse => {
        const playlistId = jsonResponse.id;
        return fetch(`https://api.spotify.com/v1/users/${userId}/playlists/${playlistId}/tracks`, {
          headers: headers,
          method: 'POST',
          body: JSON.stringify({uris: trackUris})
        });
      });
    });
  }
};

export default Spotify;
```

**Comment by saecollins** [comment]
Thanks! I did it this way because it helps me organize the information in my head to think of it as separate functions. But I can see your point and I'll work on it.
