### ISSUE TITLE
addTrack, removeTrack

### ISSUE THREAD

**Issue by farishkash** [saecollins/jamming_project#3]
https://github.com/saecollins/jamming_project/blob/3e5c76aa3fce5c3abedd3500fedb0d7038aa9624/src/components/App/App.js#L26-L33

https://github.com/saecollins/jamming_project/blob/3e5c76aa3fce5c3abedd3500fedb0d7038aa9624/src/components/App/App.js#L37-L42

 I feel like you aren't taking advantage of some  es6 features.  I want to give a couple ways to approach this using your code and wording.

Spread Operator  -  for add track

```
  addTrack(track) {
    if (this.state.playlistTracks.find(playTrack =>
      playTrack.id === track.id)) {
        return;
    }
     let clone = this.state.playlistTracks;
    this.setState({playlistTracks: [...clone, track]});
  }
```

Filter  - for remove track

```
  removeTrack(track) {
    let clone = this.state.playlistTracks;
    clone = clone.filter(cloneTrack => cloneTrack.id !== track.id);

    this.setState({playlistTracks: clone});
  }
```

**Comment by saecollins** [comment]
Thank you! I'll update.
