### ISSUE TITLE
Playlist question in comments

### ISSUE THREAD

**Issue by farishkash** [saecollins/jamming_project#4]
https://github.com/saecollins/jamming_project/blob/3e5c76aa3fce5c3abedd3500fedb0d7038aa9624/src/components/Playlist/Playlist.js#L37-L42

This is intended and how it is programmed to work in React.  The default value is only for the initial load and will never change with the state change.  Second comment down.

https://github.com/facebook/react/issues/4101

**Comment by saecollins** [comment]
Changed back to defaultValue! :) I was under the impression that the input field is supposed to reset like the playlist.
