### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [saecollins/jamming_project#5]
Overall met expectations.

It seems to me, you are used to older javascript syntax which to me explains your use of return statements.  That is perfectly fine and I know a lot of technical interviews who will focus on being able to handle the older syntax over the new ES6 standards.  And in doing so, you did this project very well.  My issues were more about taking advantage of what the new syntax has to offer.

I didn't make this an issue but I would note that with how React does component structure, the React way to approach this is to make the Track Preview a separate component.  Good job on this though, the majority of submissions completely avoid this.

Good luck on your feature request.

**Comment by saecollins** [comment]
Separated the Track Preview into a separate component. Thanks for the feedback!
