### ISSUE TITLE
Feature Request Review

### ISSUE THREAD

**Issue by mp1pro** [saecollins/jamming_project#7]
Allowing data and accessToken to persist throughout the lifecycle of the app will definitely improve the interface and functionality of the app. Using localStorage to store the information in the users's browser is a great approach. Very nice also storing playListTracks and searchTearm to the localStorage. Also remember to link the searchTerm to the connecting searchResults. In terms of dealing with the expiration of the accessToken, the best option is to notify the user of the logout and re-login process. You could also create a flow process that will have a page over the authorization page that creates a one click process to get a new acessToken. The technical desiign is practical and implementable. Great job.

**Comment by saecollins** [comment]
Thank you!
